name: interpolate
description: Foundation for embedding DSL's in Dart.
version: 0.0.1
author: <Jim Heyne> <jheyne@gmail.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
  analyzer: 'any'
dependencies:
  barback: any
dev_dependencies:
  test: 'any'
